#+OPTIONS: num:nil toc:nil
#+REVEAL_TRANS: linear
#+REVEAL_THEME: black
#+Title: Tesis
#+Author: Irvin Pereyra
#+Email: irvin.jair.pg@gmail.com
* TEMA
  Identificación no paramétrica de un motor dc por medio de un modelo de machine learning para sintonizar un controlador PID de velocidad aplicando algoritmos genéticos
* Realidad problemática
  Mientras mejor sea el controlador PID, incrementará la eficiencia y competitividad de una empresa, y es la clave para la fabricación sostenible
  Para la industria a gran escala, los enfoques tradicionales basados en modelos obtenidos a partir de principios primarios se han vuelto poco prácticos
  algoritmos evolutivos, bioinspirados, pero usan la función de transferencia en el proceso de sintonización
  función transferencia, solo sistemas lineales o aproximaciones lineales alrededor de un punto de equilibrio de interés
  SVM, LASSO para identificar sistemas dinámicos
  Por lo tanto, se presenta un escenario idóneo en el que los procesos de sintonización de controladores usando algoritmos genéticos podrían utilizar modelos de machine learning, como estimadores estadísticos o máquinas de soporte vectorial, que ofrezcan muchas más prestaciones y capacidades al momento de identificar una planta de control.
  
  El control PID es el método de control más ampliamente usado en la industria debido a su facilidad de ajuste y puesta en servicio.
  Por lo que la investigación respecto de esta estrategia de control se ha centrado principalmente en desarrollar metodologías para hallar los tres parámetros PID que convengan más a un proceso.
  Y aunque las técnicas como las propuestas por Ziegler-Nichols se ha probado muchas veces con resultados muy pobres, todavía son un punto de referencia para sintonizar controladores PID.
  Y así, muchas estrategias de sintonización pueden descartarse si se comparan con un PID bien ajustado.
  Sin embargo, algoritmos inspirados en la biología como los algoritmos genéticos o de colonia de hormigas, han demostrado
* Problema
  ¿Cómo identificar un motor dc a través de una mejor estructura de modelo que la función de transferencia, para usarse como planta de control durante la sintonización basada en algoritmos genéticos de un controlador PID de velocidad?
* Justificación

* Speaker here
#+BEGIN_NOTES
Ecnter speaker notes here.
#+END_NOTES
* Simple slide
  There be text here!
* Slide with an image background (remove this text)
:PROPERTIES:
:reveal_background: path/to/image
:reveal_background_size: x00px
:reveal_background_trans: slide
:END:
* Yet another slide
* Questions?
* Connect with Me
- Web: [YOUR WEBSITE]
- Twitter: [YOUR TWITTER HANDLE]
- Blog: [YOUR BLOG]
  
